version: "3.7"

services:
  go-db:
    image: mysql:latest
    volumes:
      - ./db/init-go-db.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: go

  app:
    image: golang:latest
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    command: go run -mod=vendor main.go
    ports:
      - "8090:8090"
    depends_on:
      - go-db

  php-db:
    image: mysql:latest
    volumes:
      - ./db/init-php-db.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: php

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: php -S 0.0.0.0:8000
    depends_on:
      - php-db
